---
title: "scratch"
output: html_document
---
## This file used for testing code in Shiny app outside of running the app 

```{r}
library(tidyverse)
library(glue)
library(readxl)
```

```{r}
# clear workspace
rm(list = ls())
```


```{r}
# read in school district data
districts <- read_csv('data/districts.csv', show_col_types = FALSE) |> 
  filter(system_name != 'State of Tennessee')

school_testing = read_excel('data/tn_state_data.xlsx', na="NA") |> 
  filter(subgroup == 'All Students' & grade == 'All Grades' & str_detect(school_name, "High School"))
```

```{r}
choices = unique(districts$system_name |> sort())
```



```{r}
filtered_data <- school_testing |> 
            filter(
                (system_name == "Hamilton County") & 
                    subject == "Algebra II"
            ) |> 
            filter(
                !str_detect(pct_below_bsc, "\\*") & 
                !str_detect(pct_bsc, "\\*") & 
                !str_detect(pct_prof, "\\*") & 
                !str_detect(pct_adv, "\\*")
            )
        
        if (nrow(filtered_data) == 0) {
            return(NULL) # Safely handle empty plots
        }
        
        filtered_data |> 
            select(school_name, subject, grade, pct_below_bsc:pct_adv) |> 
            rowwise() |> 
            mutate_at(vars(pct_below_bsc:pct_adv), as.numeric) |> 
            mutate(total = sum(c_across(pct_below_bsc:pct_adv))) |> 
            pivot_longer(
                cols = c(pct_below_bsc, pct_bsc, pct_prof, pct_adv),
                names_to = "Performance_Level",
                values_to = "Percentage"
            ) |> 
            drop_na('Percentage') |> 
            mutate(
                Performance_Level = factor(
                    Performance_Level, 
                    levels = c("pct_below_bsc", "pct_bsc", "pct_prof", "pct_adv") # Correct order
                )
            ) |> 
            ggplot(aes(x = school_name, y = Percentage, fill = Performance_Level)) +
            geom_bar(stat = "identity", position = "stack") +
            labs(
                title = 'title',
                x = "High Schools",
                y = "Percentage",
                caption = '*Schools that did not provide data are not represented.\n**Subjects not provided are not represented',
                fill = "Performance Levels"
            ) +
            theme_minimal() +
            theme(axis.text.x = element_text(angle = 45, hjust = 1),
            plot.caption.position = 'plot')
```

